"""empty message

Revision ID: 8fc671c53705
Revises: 470358acfc3f
Create Date: 2024-10-04 19:57:03.622195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fc671c53705'
down_revision: Union[str, None] = '470358acfc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('case_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'question', 'case', ['case_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_column('question', 'case_id')
    # ### end Alembic commands ###
